[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/app.html"
  status = 200
  force = true

[[headers]]
  for = "/app.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/supabase-config.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
